stand: develop
front:
  sdex:
    url: webfront-develop.dev.n-t.io
    login: nt
    password: nt-develop-2019
  admin:
    url: webadminpanel-front-develop.dev.n-t.io
    login: nt
    password: nt-develop-2019
  atm:
    url: atm-front-develop.atm-dev.n-t.io
    login: atomyze
    password: 13AtomyzE37
  atm_admin:
    url: admin-front-develop.atm-dev.n-t.io
    login: atomyze
    password: 13AtomyzE37
services:
  kyx:
    front:
      url: ky-front-develop.dev.n-t.io
      login: nt
      password: nt-develop-2019
    grpc:
      host: kyx-develop.dev.n-t.io
      port: 443
  webback:
    grpc:
      host: webback-develop.dev.n-t.io
      port: 443
    namespace: test
  ledger:
    grpc:
      host: 34.90.105.32
      port: 50051
    tool:
      base: XRP
      quote: XLM
  sum-sub:
    url: https://test-api.sumsub.com
    login: n-t.io_vladimir_tarusov_test
    password: KycKybntio