stand: prod
front:
  sdex:
    url: webfront-prod.sym-web.n-t.io
    login: symbridge
    password: bUcBwsqT7aKux3Se
  admin:
    url: webadminpanel-front-prod.sym-web.n-t.io
    login: symbridge
    password: bUcBwsqT7aKux3Se
  atm:
    url: atm-front-preprod.atm-rs.n-t.io
    login: atomyze
    password: 24AtomyzE48
  atm_admin:
    url: admin-front-preprod.atm-rs.n-t.io
    login: atomyze
    password: 24AtomyzE48
services:
  kyx:
    front:
      url: ky-front-prod.sym-web.n-t.io
      login: symbridge
      password: bUcBwsqT7aKux3Se
    grpc:
      host: kyx-ky-prod.sym-web.n-t.io
      port: 443
  webback:
    grpc:
      host: apifix-ws-webback-webback-prod.dev.n-t.io
      port: 443
    namespace: test
  ledger:
    grpc:
      host: 34.90.105.32
      port: 50051
    tool:
      base: ETH
      quote: ETC
  sum-sub:
    url: https://test-api.sumsub.com
    login: n-t.io_vladimir_tarusov_test
    password: KycKybntio